### ISSUE TITLE
Not showing in the Node-Red Flows

### ISSUE THREAD

**Issue by Sinevia** [rozek/node-red-contrib-reusable-flows#1]
Hi @rozek 

The package looks quite nice and I wanted to give it a try. But its not showing on the Node Red website which is a show stopper as it does not appear in the palette. Is there a way you can do this. If you haven't done this before the process is quite simple really, all it takes is to push it to NPM.

Also can you add release versions so that we know at what stage it is - early development, stable, etc - whether we can use with confidence :)

Many thanks

**Comment by rozek** [comment]
Sounds like a good idea - just give me some minutes...

**Comment by rozek** [comment]
actually, it **has** already published to `npm` - but that is not sufficient for being part of the list you see in Node-RED.

Let me see what I can do in order to become part of that list.

**Comment by rozek** [comment]
just to be complete: you may still `npm install node-red-contrib-reusable-flows` in the base folder of your Node-RED instance and restart Node-RED - this will make my package part of your palette

**Comment by rozek** [comment]
I'm currently preparing a submission through [https://flows.nodered.org/add/node]().

What is actually missing (and should be done before submission) is a help text which can be shown by the Node-RED editor - please, give me time until this evening to write that.

**Comment by rozek** [comment]
Oops, it was simpler than expected: the package is now part of the Node-RED library and can be found alongside the well-known "node-red-contrib-actionflows" and "node-red-contrib-components".

Thank you very much for raising this issue!

**Comment by rozek** [comment]
Well, I've also just made an "official release".

Please note, that (although I'm using it on a daily basis with > 100 reused flows) this package is still not "battle-hardened" yet. Using "reusable flows" after deployment should be fairly stable, but development may still cause the one or other hiccup...

Just give it a try!

**Comment by Sinevia** [comment]
Thank you very much @rozek. You have done a great job. Cheers.

The only thing I noticed is the releases is named as string. 

I would kindly suggest following a semantic versioning as this is what most of developers are comfortable with:
https://semver.org/

Its a very simple scheme vX.Y.Z - where if X is set you know the library is considered stable, and can be used in relatively "safe" manner

**Comment by rozek** [comment]
Done.

Thanks for the hint
